services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $someDefaultValue: 'standard'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    App\Discount\:
        resource: '../src/Discount/'
        tags: ['app.discount_strategy']

    App\Discount\DiscountStrategyResolver:
        arguments:
            $strategies: !tagged_iterator app.discount_strategy
